# Generated by Django 5.2.7 on 2026-04-18 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_plan_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='student_count',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='PracticalVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('youtube_url', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
