# Generated by Django 5.2.7 on 2026-04-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_board_student_count_practicalvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
