# Generated by Django 4.2 on 2026-04-24 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
