# Generated by Django 5.2.5 on 2026-04-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_syllabus_content_syllabus_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studynote',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='notes/pdfs/'),
        ),
    ]
