# Generated by Django 5.2.7 on 2026-05-07 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_studynote_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='core.board')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='core.class')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='core.subject')),
            ],
            options={
                'ordering': ['-year', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('MCQ_PHASE', 'MCQ Phase'), ('MCQ_DONE', 'MCQ Done'), ('CQ_PHASE', 'CQ Phase'), ('CQ_PENDING', 'Pending Review'), ('GRADED', 'Graded')], default='MCQ_PHASE', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('mcq_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cq_started_at', models.DateTimeField(blank=True, null=True)),
                ('cq_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('mcq_score', models.IntegerField(default=0)),
                ('cq_score', models.IntegerField(blank=True, null=True)),
                ('total_score', models.IntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('mcq_answers', models.JSONField(default=dict)),
                ('selected_cqs', models.JSONField(default=list)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_attempts', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
                ('exam_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.exampaper')),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('exam_paper', 'student')},
            },
        ),
        migrations.CreateModel(
            name='CQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('part_a', models.TextField(blank=True)),
                ('part_b', models.TextField(blank=True)),
                ('part_c', models.TextField(blank=True)),
                ('part_d', models.TextField(blank=True)),
                ('marks_a', models.IntegerField(default=1)),
                ('marks_b', models.IntegerField(default=2)),
                ('marks_c', models.IntegerField(default=3)),
                ('marks_d', models.IntegerField(default=4)),
                ('order', models.IntegerField(default=0)),
                ('exam_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cqs', to='core.exampaper')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamPaperMCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option1', models.CharField(max_length=500)),
                ('option2', models.CharField(max_length=500)),
                ('option3', models.CharField(max_length=500)),
                ('option4', models.CharField(max_length=500)),
                ('correct_option', models.PositiveSmallIntegerField()),
                ('marks', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=0)),
                ('exam_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcqs', to='core.exampaper')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CQSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='exam/cq_answers/')),
                ('photo_a', models.ImageField(blank=True, null=True, upload_to='exam/cq_answers/')),
                ('photo_b', models.ImageField(blank=True, null=True, upload_to='exam/cq_answers/')),
                ('photo_c', models.ImageField(blank=True, null=True, upload_to='exam/cq_answers/')),
                ('photo_d', models.ImageField(blank=True, null=True, upload_to='exam/cq_answers/')),
                ('marks_given', models.IntegerField(blank=True, null=True)),
                ('teacher_comment', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cq_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.cqquestion')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cq_submissions', to='core.examattempt')),
            ],
            options={
                'unique_together': {('attempt', 'cq_question')},
            },
        ),
    ]
