# Generated by Django 5.2.7 on 2026-05-07 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_exam_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exampaper',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_papers', to='core.board'),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
