# Generated by Django 5.2.7 on 2026-05-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('bn', 'বাংলা'), ('en', 'English')], default='bn', max_length=5),
        ),
    ]
