# Generated by Django 5.2.7 on 2026-05-09 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('exam', 'Exam Paper'), ('contest', 'Contest'), ('note', 'Study Note'), ('request', 'Note Request'), ('question', 'New Question')], max_length=10),
        ),
        migrations.CreateModel(
            name='NoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=300)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FULFILLED', 'Fulfilled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_requests', to=settings.AUTH_USER_MODEL)),
                ('fulfilled_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_requests', to='core.studynote')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_requests', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_requests', to='core.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
