# Generated by Django 5.2.7 on 2026-05-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_noterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_bn',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_bn',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
