# Generated by Django 5.2.7 on 2026-05-09 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_backfill_notification_english'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='stimulus_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_stimuli/'),
        ),
        migrations.CreateModel(
            name='WrittenSolveSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_ka', models.ImageField(blank=True, null=True, upload_to='written_solves/')),
                ('photo_kha', models.ImageField(blank=True, null=True, upload_to='written_solves/')),
                ('photo_ga', models.ImageField(blank=True, null=True, upload_to='written_solves/')),
                ('photo_gha', models.ImageField(blank=True, null=True, upload_to='written_solves/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_submissions', to='core.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_solves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('student', 'question')},
            },
        ),
    ]
