# Generated by Django 6.0.5 on 2026-05-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_written_cq_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solution_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_solutions/'),
        ),
    ]
