# Generated by Django 4.2 on 2026-05-24 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0031_question_uniqueness_by_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=100)),
                ('badge_type', models.CharField(choices=[('contest', 'Contest Performance'), ('streak', 'Consistency Streak'), ('milestone', 'Participation Milestone'), ('rank', 'Rank Achievement'), ('subject', 'Subject Mastery'), ('special', 'Special / Seasonal'), ('early', 'Early Bird'), ('social', 'Community')], max_length=20)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], max_length=20)),
                ('color_hex', models.CharField(default='#6c757d', max_length=7)),
                ('earn_condition', models.TextField()),
                ('earned_by_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['badge_type', 'rarity'],
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='allow_unrated_join',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='allows_virtual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='contest_type',
            field=models.CharField(choices=[('standard', 'Standard Timed'), ('long', 'Long Challenge'), ('marathon', 'Marathon'), ('subject', 'Subject Sprint'), ('grand', 'Grand Contest'), ('practice', 'Practice / Unrated')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='contest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('open', 'Open for All')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='contest',
            name='entry_requirement',
            field=models.CharField(choices=[('open', 'Open to All'), ('premium', 'Premium Members Only'), ('class_9', 'Class 9 Only'), ('class_10', 'Class 10 Only'), ('class_11', 'Class 11 Only'), ('class_12', 'Class 12 Only')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='contest',
            name='hide_leaderboard_until_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='is_multi_stage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='is_rated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='max_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='parent_contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages', to='core.contest'),
        ),
        migrations.AddField(
            model_name='contest',
            name='prize_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='ratings_calculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='sponsor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contest',
            name='stage_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contest',
            name='tags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='contest',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='is_rated_participant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='is_virtual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='percentile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='rank_in_contest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='rating_after',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='rating_before',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='rating_change',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='time_taken_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='solution_image',
            field=models.FileField(blank=True, null=True, upload_to='question_solutions/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='stimulus_image',
            field=models.FileField(blank=True, null=True, upload_to='question_stimuli/'),
        ),
        migrations.CreateModel(
            name='VirtualContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('virtual_rank', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_attempts', to='core.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_contests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1000)),
                ('peak_rating', models.IntegerField(default=1000)),
                ('contests_entered', models.IntegerField(default=0)),
                ('contests_rated', models.IntegerField(default=0)),
                ('best_rank', models.IntegerField(blank=True, null=True)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_contest_date', models.DateField(blank=True, null=True)),
                ('total_score_earned', models.IntegerField(default=0)),
                ('coin_balance', models.IntegerField(default=0)),
                ('last_checkin_date', models.DateField(blank=True, null=True)),
                ('checkin_streak', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContestRatingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_rating', models.IntegerField()),
                ('new_rating', models.IntegerField()),
                ('change', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('percentile', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ContestCoinLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('contest_participate', 'Contest Participation'), ('contest_top10pct', 'Top 10% Finish'), ('contest_top25pct', 'Top 25% Finish'), ('contest_top50pct', 'Top 50% Finish'), ('contest_win', 'Contest Win'), ('daily_checkin', 'Daily Check-in'), ('streak_7', 'Weekly Streak Bonus'), ('streak_30', 'Monthly Streak Bonus'), ('badge_earned', 'Badge Earned'), ('first_contest', 'First Contest'), ('early_bird', 'Early Registration'), ('virtual_complete', 'Virtual Contest Complete')], max_length=40)),
                ('amount', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_ledger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.badge')),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='ContestRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rated', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_early_bird', models.BooleanField(default=False)),
                ('notified_start', models.BooleanField(default=False)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at'],
                'unique_together': {('contest', 'user')},
            },
        ),
    ]
