# Generated by Django 6.0.5 on 2026-05-31 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_badge_contest_allow_unrated_join_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.board'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.class'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='exam_goal',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='study_subjects',
            field=models.ManyToManyField(blank=True, related_name='enrolled_students', to='core.subject'),
        ),
    ]
