# Generated by Django 6.0.5 on 2026-06-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_userprofile_plan_expires_at_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('exam', 'Exam Paper'), ('contest', 'Contest'), ('note', 'Study Note'), ('request', 'Note Request'), ('question', 'New Question'), ('payment', 'Payment')], max_length=10),
        ),
    ]
